/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_MarcosPaulo.cliente;

import controller_MarcosPaulo.ClienteController;
import controller_MarcosPaulo.ContaComumController;
import controller_MarcosPaulo.ContaEspecialController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model_MarcosPaulo.classes.Cliente;
import model_MarcosPaulo.classes.Conta;
import model_MarcosPaulo.classes.ContaEspecial;
import model_MarcosPaulo.utilidades.TipoDeConta;
import model_MarcosPaulo.interfaces.CRUDCliente;
import model_MarcosPaulo.interfaces.CRUDContaComum;
import model_MarcosPaulo.interfaces.CRUDContaEspecial;
import model_MarcosPaulo.utilidades.TableModelService;

/**
 *
 * @author marcos
 */
public class JDialogUpdate extends javax.swing.JDialog {

    private CRUDCliente cliControll = null;
    private CRUDContaComum ccControll = null;
    private CRUDContaEspecial ceControll = null;
    private Cliente cliente = null;

    /**
     * Creates new form JDialogUpdate
     */
    public JDialogUpdate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ImageIcon icone = new ImageIcon("assets/icons/userEdit.png");
        setIconImage(icone.getImage());

        this.cliControll = new ClienteController("db/cliente.txt");
        this.ccControll = new ContaComumController("db/contaComum.txt");
        this.ceControll = new ContaEspecialController("db/contaEspecial.txt");
    }

    /**
     * Creates new form JDialogUpdate
     */
    public JDialogUpdate(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        initComponents();

        ImageIcon icone = new ImageIcon("assets/icons/userEdit.png");
        setIconImage(icone.getImage());

        try {
            this.cliControll = new ClienteController("db/cliente.txt");
            this.ccControll = new ContaComumController("db/contaComum.txt");
            this.ceControll = new ContaEspecialController("db/contaEspecial.txt");

            this.cliente = cliente;

            jTextFieldNome.setText(cliente.getNome());
            jTextFieldEmail.setText(cliente.getEmail());
            String tipoDeConta = String.format("" + cliente.getTipoDeConta()).toLowerCase();
            String aux = Character.toUpperCase(tipoDeConta.charAt(0)) + tipoDeConta.substring(1);
            jComboBoxTipoDeConta.setSelectedItem("Conta " + aux);
            String saida = (cliente.getTipoDeConta().equals(TipoDeConta.ESPECIAL))
                    ? "" + this.ceControll.findByClienteId(cliente.getId()).getLimite() : "";

            jTextFieldLimite.setText(saida);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlterarCliente = new javax.swing.JPanel();
        jLabelNovoCliente = new javax.swing.JLabel();
        jPanelForm = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxTipoDeConta = new javax.swing.JComboBox<>();
        jLabelTipoDeConta = new javax.swing.JLabel();
        jLabelLimite = new javax.swing.JLabel();
        jTextFieldLimite = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Cliente - v1.0.0.0");
        setResizable(false);

        jLabelNovoCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelNovoCliente.setText("Alterar Cliente");

        jPanelForm.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNome.setText("NOME");

        jLabelEmail.setText("EMAIL");

        jComboBoxTipoDeConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Conta Comum", "Conta Especial" }));
        jComboBoxTipoDeConta.setToolTipText("");
        jComboBoxTipoDeConta.setEnabled(false);
        jComboBoxTipoDeConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDeContaActionPerformed(evt);
            }
        });

        jLabelTipoDeConta.setText("TIPO DE CONTA");

        jLabelLimite.setText("LIMITE");

        jTextFieldLimite.setEnabled(false);

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jTextFieldNome)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoDeConta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelTipoDeConta))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFormLayout.createSequentialGroup()
                                .addComponent(jLabelLimite)
                                .addGap(0, 85, Short.MAX_VALUE))
                            .addComponent(jTextFieldLimite))))
                .addContainerGap())
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoDeConta)
                    .addComponent(jLabelLimite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoDeConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlterarClienteLayout = new javax.swing.GroupLayout(jPanelAlterarCliente);
        jPanelAlterarCliente.setLayout(jPanelAlterarClienteLayout);
        jPanelAlterarClienteLayout.setHorizontalGroup(
            jPanelAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlterarClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar))
                    .addGroup(jPanelAlterarClienteLayout.createSequentialGroup()
                        .addGroup(jPanelAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNovoCliente)
                            .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAlterarClienteLayout.setVerticalGroup(
            jPanelAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNovoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanelAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAlterarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoDeContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDeContaActionPerformed
        // TODO add your handling code here:
        jTextFieldLimite.setEnabled(jComboBoxTipoDeConta.getSelectedItem().toString().equals("Conta Especial"));
    }//GEN-LAST:event_jComboBoxTipoDeContaActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        try {
            if (jComboBoxTipoDeConta.getSelectedIndex() == 0) {
                throw new Exception("Selecione o tipo de conta!");
            }
            String nome = jTextFieldNome.getText();
            String email = jTextFieldEmail.getText();
            String tipoDeConta = jComboBoxTipoDeConta.getSelectedItem().toString().split(" ")[1];
            
            this.cliente.setNome(nome);
            this.cliente.setEmail(email);

            Conta conta = (cliente.getTipoDeConta().equals(TipoDeConta.COMUM))
                    ? ccControll.findByClienteId(this.cliente.getId())
                    : ceControll.findByClienteId(this.cliente.getId());

            if ((tipoDeConta.toUpperCase().equals("ESPECIAL"))) {
                Double limite = Double.parseDouble(jTextFieldLimite.getText());
                ((ContaEspecial)conta).setLimite(limite);
                ceControll.update((ContaEspecial)conta);
            }
            cliente.setNumeroConta(conta.getNumero());
            cliente.setTipoDeConta(conta.getTipoDeConta());

            cliControll.update(cliente);
            TableModelService.getInstance().update();

            this.dispose();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogUpdate dialog = new JDialogUpdate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxTipoDeConta;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLimite;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNovoCliente;
    private javax.swing.JLabel jLabelTipoDeConta;
    private javax.swing.JPanel jPanelAlterarCliente;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLimite;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
