/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_MarcosPaulo.conta;

import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import model_MarcosPaulo.classes.Cliente;
import model_MarcosPaulo.classes.Conta;
import model_MarcosPaulo.classes.ContaEspecial;
import model_MarcosPaulo.utilidades.TipoDeConta;

/**
 *
 * @author marcos
 */
public class JDialogExtrato extends javax.swing.JDialog {
    /**
     * Creates new form JDialogExtrato
     * @param parent
     * @param modal
     */
    public JDialogExtrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icone = new ImageIcon("assets/icons/dinheiro.png");
        setIconImage(icone.getImage());
        this.jLabelExtrato.setText("Extrato");
    }
    

        /**
     * Creates new form JDialogExtrato
     * @param parent
     * @param modal
     * @param Extrato
     */
    public JDialogExtrato(java.awt.Frame parent, boolean modal,Cliente cliente,Conta conta) {
        super(parent, modal);
        initComponents();
        ImageIcon icone = new ImageIcon("assets/icons/dinheiro.png");
        setIconImage(icone.getImage());
        jLabelExtrato.setText(formatString(cliente, conta));
    }
    
    public static String formatString( Cliente cliente,Conta conta){
        String extrato = "---------------------------------------------------------------------------------------------------------\n";
        extrato += "NOME:......................" + cliente.getNome().toUpperCase()+"\n";
        extrato += "EMAIL:......................" + cliente.getEmail()+"\n";
        extrato += "---------------------------------------------------------------------------------------------------------\n";        
        extrato += "CONTA "+((conta.getTipoDeConta() == TipoDeConta.COMUM)?conta.getTipoDeConta()+"":conta.getTipoDeConta())+":......"+conta.getNumero()+"\n";                        
        extrato += "SALDO ATUAL:..........." + formatMoney(conta.getSaldo())+"\n";
        extrato += (conta.getTipoDeConta() == TipoDeConta.COMUM)? "" :"LIMITE:......................"+ formatMoney(((ContaEspecial)conta).getLimite())+"\n";
        extrato += "---------------------------------------------------------------------------------------------------------\n";
        extrato += "" + conta.getExtrato().getTransacoes();
        extrato += "---------------------------------------------------------------------------------------------------------\n";
        return extrato;
    }
    public static String formatMoney(double valorBigDecimal) {
        return new DecimalFormat("'R$ ' #,###,##0.00").format(valorBigDecimal);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelExtrato = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Extrato Bancário - v1.0.0.0");

        jLabelExtrato.setEditable(false);
        jLabelExtrato.setColumns(20);
        jLabelExtrato.setRows(5);
        jScrollPane1.setViewportView(jLabelExtrato);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogExtrato dialog = new JDialogExtrato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jLabelExtrato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
