package view_MarcosPaulo.conta;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import controller_MarcosPaulo.ContaComumController;
import controller_MarcosPaulo.ContaEspecialController;
import java.text.DecimalFormat;
import model_MarcosPaulo.classes.Cliente;
import model_MarcosPaulo.classes.Conta;
import model_MarcosPaulo.classes.ContaEspecial;
import model_MarcosPaulo.utilidades.TipoDeConta;
import model_MarcosPaulo.interfaces.CRUDContaComum;
import model_MarcosPaulo.interfaces.CRUDContaEspecial;
import model_MarcosPaulo.utilidades.JLabelSaldoService;
import view_MarcosPaulo.JFrameLogin;

/**
 *
 * @author marcos
 */
public class JFrameConta extends javax.swing.JFrame {

    private CRUDContaComum ccControll = null;
    private CRUDContaEspecial ceControll = null;
    private Cliente cliente = null;
    private Conta conta = null;

    /**
     * Creates new form JFrameClienteRead
     */
    public JFrameConta() {
        super("Conta - v1.0.0.0");
        initComponents();

        ImageIcon icone = new ImageIcon("assets/icons/dinheiro.png");
        setIconImage(icone.getImage());

        try {            
            this.ccControll = new ContaComumController("db/contaComum.txt");
            this.ceControll = new ContaEspecialController("db/contaEspecial.txt");

            this.cliente = new Cliente();
            this.conta = new Conta(0, 0){};

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }

    /**
     * Creates new form JFrameClienteRead
     *
     * @param cliente
     */
    public JFrameConta(Cliente cliente) {
        super("Conta");
        initComponents();

        ImageIcon icone = new ImageIcon("assets/icons/dinheiro.png");
        setIconImage(icone.getImage());

        try {           
            this.ccControll = new ContaComumController("db/contaComum.txt");
            this.ceControll = new ContaEspecialController("db/contaEspecial.txt");
            this.cliente = cliente;

            conta = (this.cliente.getTipoDeConta().equals(TipoDeConta.COMUM))
                    ? ccControll.findByClienteId(this.cliente.getId())
                    : ceControll.findByClienteId(this.cliente.getId());

            this.setValuesLabel();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }
    /**
     * 
     */
    public void setValuesLabel(){
            jLabelConta.setText(this.cliente.getNome());
            jLabelTipoDeConta.setText((this.cliente.getTipoDeConta().equals(TipoDeConta.COMUM)) ? "Conta Comum" : "Conta Especial");
            jLabelEmail.setText(cliente.getEmail());
            
            JLabelSaldoService label = JLabelSaldoService.getInstance();
            label.setConta(conta);
            label.setLabelSaldo(jLabelSaldo);
            label.updateLabelSaldo();
            String text = (this.conta.getTipoDeConta().equals(TipoDeConta.ESPECIAL)) ? "LIMITE:...." + formatMoney(((ContaEspecial) conta).getLimite()) : "";
            jLabelLimite.setText(text);                    
 
    }
    public String formatMoney(double valorBigDecimal) {
        return new DecimalFormat("'R$ ' #,###,##0.00").format(valorBigDecimal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButtonSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelConta = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelLimite = new javax.swing.JLabel();
        jLabelTipoDeConta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSaque = new javax.swing.JButton();
        jButtonDeposito = new javax.swing.JButton();
        jButtonTransferencia = new javax.swing.JButton();
        jButtonExtrato = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conta - v1.0.0.0");
        setResizable(false);

        jButtonSair.setBackground(java.awt.Color.white);
        jButtonSair.setIcon(new javax.swing.ImageIcon("/home/marcos/development/NetBeans/NetbeansProject/ProjetoMVC/assets/icons/voltar.png")); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelConta.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelConta.setText("Conta");

        jLabelSaldo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSaldo.setText("Saldo");

        jLabelLimite.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelLimite.setText("limite");

        jLabelTipoDeConta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTipoDeConta.setText("Tipo de Conta");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSaque.setIcon(new javax.swing.ImageIcon("/home/marcos/development/NetBeans/NetbeansProject/ProjetoMVC/assets/icons/retirar.png")); // NOI18N
        jButtonSaque.setText("SAQUE");
        jButtonSaque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaqueActionPerformed(evt);
            }
        });

        jButtonDeposito.setIcon(new javax.swing.ImageIcon("/home/marcos/development/NetBeans/NetbeansProject/ProjetoMVC/assets/icons/deposito.png")); // NOI18N
        jButtonDeposito.setText("DEPÓSITO");
        jButtonDeposito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDeposito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoActionPerformed(evt);
            }
        });

        jButtonTransferencia.setIcon(new javax.swing.ImageIcon("/home/marcos/development/NetBeans/NetbeansProject/ProjetoMVC/assets/icons/transferir.png")); // NOI18N
        jButtonTransferencia.setText("TRANSFERÊNCIA");
        jButtonTransferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTransferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferenciaActionPerformed(evt);
            }
        });

        jButtonExtrato.setIcon(new javax.swing.ImageIcon("/home/marcos/development/NetBeans/NetbeansProject/ProjetoMVC/assets/icons/extrato.png")); // NOI18N
        jButtonExtrato.setText("EXTRATO");
        jButtonExtrato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExtrato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExtrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTransferencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEmail.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelConta)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelTipoDeConta)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelLimite, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelSaldo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTipoDeConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLimite)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 182, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        new JFrameLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaqueActionPerformed
        // TODO add your handling code here:
       JDialogSaque dialog = new JDialogSaque(new javax.swing.JFrame(), true, conta);
       dialog.setVisible(true);
    }//GEN-LAST:event_jButtonSaqueActionPerformed

    private void jButtonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoActionPerformed
        // TODO add your handling code here:
       JDialogDeposito dialog = new JDialogDeposito(new javax.swing.JFrame(), true, conta);
       dialog.setVisible(true);
    }//GEN-LAST:event_jButtonDepositoActionPerformed

    private void jButtonTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferenciaActionPerformed
        // TODO add your handling code here:
        JDialogTransferencia dialog = new JDialogTransferencia(new javax.swing.JFrame(), true,conta);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonTransferenciaActionPerformed

    private void jButtonExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtratoActionPerformed
        // TODO add your handling code here:
        JDialogExtrato dialog = new JDialogExtrato(new javax.swing.JFrame(), true,cliente,conta);
        dialog.setVisible(true);        
    }//GEN-LAST:event_jButtonExtratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonExtrato;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSaque;
    private javax.swing.JButton jButtonTransferencia;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabelConta;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLimite;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelTipoDeConta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
